language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

addons:
  apt:
    packages:
      ant

env:
  - ILLUMINATE_VERSION=5.0.*

matrix:
  include:
    - php: 7.0
      env: ILLUMINATE_VERSION=5.1.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.2.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.8.*
    - php: 7.0
      env: ILLUMINATE_VERSION=6.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.1.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.2.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.8.*
    - php: 7.1
      env: ILLUMINATE_VERSION=6.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.1.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.2.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.8.*
    - php: 7.2
      env: ILLUMINATE_VERSION=6.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.1.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.2.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.8.*
    - php: 7.3
      env: ILLUMINATE_VERSION=6.*
    - php: 7.4
      env: ILLUMINATE_VERSION=5.1.*
    - php: 7.4
      env: ILLUMINATE_VERSION=5.2.*
    - php: 7.4
      env: ILLUMINATE_VERSION=5.3.*
    - php: 7.4
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.4
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.4
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.4
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.4
      env: ILLUMINATE_VERSION=5.8.*
    - php: 7.4
      env: ILLUMINATE_VERSION=6.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.1.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.2.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.3.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.4.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.5.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.6.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.7.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.8.*
    - php: nightly
      env: ILLUMINATE_VERSION=6.*
  fast_finish: true
  allowed_failures:
    - php: nightly

before_install:
  - composer self-update
  - test "${ILLUMINATE_VERSION}" = '5.0.*' && composer require "phpunit/phpunit:~5.0" --no-update --dev
  - test "${ILLUMINATE_VERSION}" = '5.1.*' && composer require "phpunit/phpunit:~5.0" --no-update --dev
  - test "${ILLUMINATE_VERSION}" = '5.2.*' && composer require "phpunit/phpunit:~5.0" --no-update --dev
  - test "${ILLUMINATE_VERSION}" = '5.3.*' && composer require "phpunit/phpunit:~5.0" --no-update --dev
  - test "${ILLUMINATE_VERSION}" = '5.4.*' && composer require "phpunit/phpunit:~5.0" --no-update --dev
  - test "${ILLUMINATE_VERSION}" = '5.5.*' && composer require "phpunit/phpunit:~6.0" "mockery/mocker:~1.0" --no-update --dev
  - test "${ILLUMINATE_VERSION}" = '5.5.*' && composer require "phpunit/phpunit:~6.0" "mockery/mocker:~1.0" --no-update --dev
  - test "${ILLUMINATE_VERSION}" = '5.6.*' && composer require "phpunit/phpunit:~7.0" "mockery/mocker:~1.0" --no-update --dev
  - test "${ILLUMINATE_VERSION}" = '5.7.*' && composer require "phpunit/phpunit:~7.0" "mockery/mocker:~1.0" --no-update --dev
  - test "${ILLUMINATE_VERSION}" = '5.8.*' && composer require "phpunit/phpunit:~7.0" "mockery/mocker:~1.0" --no-update --dev
  - test "${ILLUMINATE_VERSION}" = "6.*"   && composer require "phpunit/phpunit:~8.0" "mockery/mocker:~1.0" --no-update --dev
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update

install:
  - composer install --prefer-source --no-interaction

script:
  - ant

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml

notifications:
  email: false
